version: 2
jobs:
  make-eksctl-image:
    # use machine build, as otherwise we cannot use make and have to duplicate makefile
    machine:
      image: ubuntu-1604:201903-01
    environment:
        GO_VERSION: 1.12.6
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - run:
            name: Install Golang (needed for dependency calculation)
            command: |
                curl -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
                tar -xf go${GO_VERSION}.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go
                sudo mv go /usr/local
                mkdir -p "$HOME/go/bin"
                go version
      - run: mkdir -p ./test-results/ginkgo
      - run: make eksctl-image
      - run: sudo chown -R circleci.circleci /home/circleci/.cache/go-build/ /home/circleci/go/pkg/mod/
      - save_cache:
            key: go-cache-{{ .Branch }}-{{ .Revision }}
            paths:
                - "/home/circleci/.cache/go-build/"
                - "/home/circleci/go/pkg/mod/"
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
  make-release-candidate:
    machine:
      image: ubuntu-1604:201903-01
    environment:
        GO_VERSION: 1.12.6
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - run:
            name: Install Golang (needed for dependency calculation)
            command: |
                curl -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
                tar -xf go${GO_VERSION}.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go
                sudo mv go /usr/local
                mkdir -p "$HOME/go/bin"
                go version
      - run:
            name: Create release candidate binaries for all plaforms and upload to GitHub
            command: make release-candidate
            no_output_timeout: 21m

  make-release:
    machine:
      image: ubuntu-1604:201903-01
    environment:
        GO_VERSION: 1.12.6
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - run:
            name: Install Golang (needed for dependency calculation)
            command: |
                curl -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
                tar -xf go${GO_VERSION}.linux-amd64.tar.gz
                sudo rm -rf /usr/local/go
                sudo mv go /usr/local
                mkdir -p "$HOME/go/bin"
                go version
      - run:
            name: Create release binaries for all plaforms and upload to GitHub
            command: make release
            no_output_timeout: 21m

workflows:
  version: 2
  any-commit:
    jobs:
      - make-eksctl-image:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - make-eksctl-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
      - make-release-candidate:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+/
      - make-release:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
